% this controls the login screen
function loginScreen
close all
clear classes

    loginFigure = figure;
    fpos = get(loginFigure,'Position');
    set(loginFigure,'Units','pixels',...
                    'Position',[fpos(1:2),300,100],...
                    'NumberTitle','off',...
                    'Name','Welcome to Word Tower!',...
                    'MenuBar','none',...
                    'DockControls','off',...
                    'Resize','off',...
                    'WindowStyle','modal')
    
    mainPanel = uipanel(loginFigure,'Units','normalized','Position',[0 0 1 1]);
    
    % Entering the name
    nameLabel = uicontrol('Parent',mainPanel,...
                            'Style','text',...
                            'String','Name: ',...
                            'Units', 'normalized',...
                            'FontSize',10,...
                            'Position',[.15 .60 .2 .25]);
    
    nameField = uicontrol('Parent',mainPanel,...
                            'Style','edit',...
                            'Units', 'normalized',...
                            'BackgroundColor',[1 1 1],...
                            'Position',[.4 .68 .5 .25],...
                            'KeyPressFcn', @enter_login);

    % Entering the password
    pwLabel = uicontrol('Parent',mainPanel,...
                            'Style','text',...
                            'String','Password: ',...
                            'Units', 'normalized',...
                            'FontSize',10,...
                            'Position',[.15 .27 .2 .25]);

%%%% Since matlab does not have an easy implementation of password visual
%%%% protection, I'm going to us JPasswordField which is implemented in
%%%% Java. - Simon

% Java implementation

    pwField = javax.swing.JPasswordField();
    [pwField, hEditPassword] = javacomponent(pwField, [120 32 150 23], loginFigure);
    pwField.setFocusable(true);

    set(hEditPassword, ...
        'Parent', loginFigure, ...
        'Units', 'normalized', ...
        'Position',[.41 .35 .48 .20]);
    drawnow;  


    loginButton = uicontrol('Parent',mainPanel,...
                            'Style', 'pushbutton',...
                            'Units','normalized',...
                            'Position', [.12 .05 .3 .22],...
                            'String','Login',...
                            'Callback', @login,...
                            'KeyPressFcn',@enter_login);
    
    gotoCreateUser = uicontrol('Parent',mainPanel,...
                            'Style', 'pushbutton',...
                            'Units','normalized',...
                            'Position', [.52 .05 .3 .22],...
                            'String','New User',...
                            'Callback', @createNewWrapper,...
                            'KeyPressFcn', @enter_createNewWrapper);
    
    function login(h,e) %callback for logging into the game.
        name = get(nameField,'String');
        password = char(pwField.Password);
        password = password'; %inverting the password
        
        if isempty(name)
            errordlg('Must enter name')
        elseif isempty(password)
            errordlg('Must enter password')
        else
            [exist,loginPlayer] = Player.getPlayer(name);
            %first check if the player exists
            %if they exist, then check password
            if exist == false
                errordlg('User Doesnt Exist!')
            elseif ~isequal(password,loginPlayer.password)
                errordlg('Incorrect Password')
            else
                panel = GamePanel;
                panel.currentPlayer = loginPlayer;
                panel.gamePanelUI
            end
        end
    end

    function enter_login(h,e) % callback for hitting enter
        if e.Character == 13
            login
        end
    end

    function createNewWrapper(h,e) %wrapper function
        %first close the login screen
        close(loginFigure)
        %call Player static method
        Player.displayMakeProfile
    end

    function enter_createNewWrapper(h,e) % hitting enter to create new
        if e.Character == 13
            createNewWrapper
        end
    end

    uicontrol(nameField)
end